services:
  sdl2-display:
    environment:
      - XAUTHORITY=/tmp/.Xauthority
      - PULSE_SERVER=unix:/run/user/${UID:-1000}/pulse/native
      - XDG_RUNTIME_DIR=/run/user/${UID:-1000}
    volumes:
      - ${XAUTHORITY}:/tmp/.Xauthority:ro
      - /run/user/${UID:-1000}:/run/user/${UID:-1000}
